services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: "12345678"
        ports:
            - "3306:3306"

    ghost:
        image: ghost:latest
        restart: always
        ports:
            - 2368:2368
        environment:
            database__client: mysql
            database__connection__host: mysql
            database__connection__user: root
            database__connection__password: randompassword
            database__connection__database: ghost
            url: http://localhost:2368
        #volumes:
        #    - ./config.json:/var/lib/ghost/config.production.json

    mailgun-ses:
        image: ghcr.io/tilak999/mailgun-ses-proxy:latest
        env_file:
            - .env
        ports:
            - "8080:8080"
