name: docker-build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

# permissions are needed if pushing to ghcr.io
permissions:
    packages: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Get the repository's code
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set env
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
                  
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  
            - name: Build
              uses: docker/build-push-action@v6
              with:
                  file: ./Dockerfile
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ghcr.io/${{ github.repository }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
