name: Build

# Controls when the workflow will run
on:
    workflow_dispatch:
    push:
        branches:
            - "main"

# permissions are needed if pushing to ghcr.io
permissions:
    packages: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Get the repository's code
            - name: Checkout
              uses: actions/checkout@v2
            # https://github.com/docker/setup-qemu-action
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            # https://github.com/docker/setup-buildx-action
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2
              with:
                  platforms: linux/amd64,linux/arm64
                  provenance: false
            - name: Login to GHCR
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build
              uses: docker/build-push-action@v2
              with:
                  file: ./Dockerfile
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ghcr.io/${{ github.repository }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
